### ISSUE TITLE
Polish return type of `.get()`

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/remote-settings-client#20]
Currently, the `.get()` method returns a vector of `serde_json` objects.

I think this is not a good practice, because consumers code will be bound to serde.
Changing our internal implementation should not oblige consumers to rewrite their code.

Returning Rust raw types would be more convenient.... And/or define a `Record` type.

**Comment by Vishwa-Mozilla** [comment]
I like defining a ```Record``` type

**Comment by Vishwa-Mozilla** [comment]
@ncalexan what are your thoughts?

**Comment by ncalexan** [comment]
> 
> 
> @ncalexan what are your thoughts?

Sorry, I didn't see this in the hail of mail.  I would definitely define a `Record` type.  I wouldn't alias to `serde_json::Value` because then consumers are tied to `serde_json` just the same.

If you want to, you could use the newtype pattern around `serde_json::Value` and provide some interface on top of it; but I wouldn't return the underlying type or make it public.
